name:                semiring
version:             0.1.0.0
github:              "githubuser/semiring"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/semiring#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- semirings
- csv
- optparse-applicative
- filepath
- parsec
- mtl
- transformers


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - OverloadedRecordDot
  - DuplicateRecordFields
  - LambdaCase
  - TypeSynonymInstances
  - FlexibleInstances
  - UndecidableInstances

library:
  source-dirs: src

executables:
  semiring-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - semiring

tests:
  semiring-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - semiring
    - tasty
    - tasty-hunit
    - tasty-golden
